"""Modul und Status am Lernziel ergaenzt

Revision ID: 3c4b2fb57969
Revises: 36776bba1943
Create Date: 2026-08-04 23:47:26.856281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4b2fb57969'
down_revision = '36776bba1943'
branch_labels = None
depends_on = None


def upgrade():
    # server_default versorgt bereits vorhandene Zeilen mit einem Wert.
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'module',
                sa.String(length=100),
                nullable=False,
                server_default='Nicht zugeordnet',
            )
        )
        batch_op.add_column(
            sa.Column(
                'status',
                sa.String(length=20),
                nullable=False,
                server_default='offen',
            )
        )

    # Vorgabewert wieder entfernen: Neue Datensaetze muessen echte Werte liefern.
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('module', server_default=None)
        batch_op.alter_column('status', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('module')

    # ### end Alembic commands ###
