"""Prioritaet am Lernziel ergaenzt

Revision ID: 92b49259af45
Revises: 3c4b2fb57969
Create Date: 2026-08-05 10:03:34.500243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b49259af45'
down_revision = '3c4b2fb57969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
